defaults:
  - equation_config
  - equation_var
  - prompt_var

rag_prompt: "${question_code_prompt}"
rag_vars: "${equation_input}"
user_prompt: "${question_code_prompt}"
user_vars: "${equation_input}"
system_prompt: "${system_code_prompt}"
section_name: "code"