defaults:
  - equation_config
  - prompt_var
  - _self_
rag_prompt: "${question_math_prompt}"
rag_vars: "${equation_input}"
user_prompt: "${question_math_prompt}"
user_vars: "${equation_input}"
system_prompt: "${system_math_prompt}"
section_name: "math"