db_dir: "../../data/chroma"
collection_name: "math"
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
batch_size: 512
max_records_per_dataset: 3

datasets: [
    #"math-ai/StackMathQA",
    #"meta-math/MetaMathQA", 
    #"qwedsacf/competition_math",
    "TIGER-Lab/MathInstruct",
    #"open-r1/OpenR1-Math-220k"
]

finite_diff_repos: [
    "https://github.com/zwicker-group/py-pde",
]

neural_repos: [
    "https://github.com/tum-pbs/PhiFlow",
    "https://github.com/omniscientoctopus/Physics-Informed-Neural-Networks",
]

modulus_repos: [
    "https://github.com/NVIDIA/physicsnemo",
    "https://github.com/MehdiTaghizadehUVa/MFGNN_Flood",
]

